title: Gabriel Capilla
description: Open Source Enthusiast
url: http://gabrielcapilla.github.io
baseurl: ""
theme: null

sass:
  style: compressed

plugins:
  - jekyll-redirect-from

collections:
  docs:
    output: false
    sort_by: order
  projects:
    output: true

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - .gitignore
