title: Gabriel Capilla
description: Open Source Enthusiast
url: "https://gabrielcapilla.github.io"
baseurl: ""
theme: null

sass:
  style: compressed
  sass_dir: _sass

# plugins:
#   - jekyll-redirect-from

collections:
  docs:
    output: false
    sort_by: order
  projects:
    output: true

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - .gitignore
